// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCbz(arg1, arg2, arg3, arg4) {
  return window['go']['application']['App']['ExportCbz'](arg1, arg2, arg3, arg4);
}

export function ExportXml(arg1, arg2) {
  return window['go']['application']['App']['ExportXml'](arg1, arg2);
}

export function GetAllGenreInput() {
  return window['go']['application']['App']['GetAllGenreInput']();
}

export function GetAllPublisherInput() {
  return window['go']['application']['App']['GetAllPublisherInput']();
}

export function GetAllTagInput() {
  return window['go']['application']['App']['GetAllTagInput']();
}

export function GetComicInfo(arg1) {
  return window['go']['application']['App']['GetComicInfo'](arg1);
}

export function GetDirectory() {
  return window['go']['application']['App']['GetDirectory']();
}

export function GetDirectoryWithDefault(arg1) {
  return window['go']['application']['App']['GetDirectoryWithDefault'](arg1);
}

export function QuickExportKomga(arg1) {
  return window['go']['application']['App']['QuickExportKomga'](arg1);
}

export function StartUpTest(arg1, arg2) {
  return window['go']['application']['App']['StartUpTest'](arg1, arg2);
}
