// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {comicinfo} from '../models';

export function GetComicInfo(arg1:string):Promise<comicinfo.ComicInfo|string>;

export function GetDirectory():Promise<string>;

export function GetDirectoryWithDefault(arg1:string):Promise<string>;

export function QuickExportKomga(arg1:string):Promise<string>;
