// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirectory() {
  return window['go']['main']['App']['GetDirectory']();
}

export function GetDirectoryWithDefault(arg1) {
  return window['go']['main']['App']['GetDirectoryWithDefault'](arg1);
}

export function QuickExportKomga(arg1) {
  return window['go']['main']['App']['QuickExportKomga'](arg1);
}
