// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirectory():Promise<string>;

export function QuickExportKomga(arg1:string):Promise<string>;
