// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCbz(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportCbz'](arg1, arg2, arg3);
}

export function ExportXml(arg1, arg2) {
  return window['go']['main']['App']['ExportXml'](arg1, arg2);
}

export function GetComicInfo(arg1) {
  return window['go']['main']['App']['GetComicInfo'](arg1);
}

export function GetDirectory() {
  return window['go']['main']['App']['GetDirectory']();
}

export function GetDirectoryWithDefault(arg1) {
  return window['go']['main']['App']['GetDirectoryWithDefault'](arg1);
}

export function QuickExportKomga(arg1) {
  return window['go']['main']['App']['QuickExportKomga'](arg1);
}
